---
title: "numeric_eda"
output: github_document
editor_options: 
  chunk_output_type: console
---
## Numeric Eda

```{r set up}
library(tidyverse)

```

## Let's import data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10, # degree C
    tmax = tmax / 10 ,
  month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

## summarize()

```{r}
weather_df %>%
  group_by(name, month) %>% 
  summarize(
    n_obs = n()
  )
```

can we count in other ways

```{r}
weather_df %>% 
  count(name, month)
```

don't use `table()`

```{r}
weather_df %>% 
  pull(month) %>% 
  table()
```

you can have multiple summaries

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(),
    n_dist= n_distinct(date)
  )
```


## a brief aside on 2X2 tables

```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(count = n()) %>% 
  pivot_wider(
    names_from =cold,
    values_from =count 
  )
```

or you can use janitor
```{r}
weather_df %>% 
  mutate(cold = case_when(
    tmax <  5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE     ~ "" # if no case is satisfied, this is always true -- to avoid a error value
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)
```

## General summaries
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs= n(),
    mean_tmax = mean(tmax, na.rm= TRUE),
    sd_prcp = sd(prcp),
    median_tmax = median(tmax, na.rm = TRUE)
  )
```


```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(across(tmin:prcp, mean))
```

this is a data frame

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax, na.rm= TRUE)) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```


```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  knitr::kable(digits = 1) #rmd structure to print out table
```

## Grouped mutates

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(mean_tmax= mean(tmax, na.rm = TRUE), 
  centered_tmax = tmax - mean_tmax) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```

```{r}
weather_df %>%
  group_by(name) %>%
  mutate(yesterday_tmax = lag(tmax),
         tmax_change = tmax- yesterday_tmax) %>% 
  summarize(
    sd_tmax_change = sd(tmax_change, na.rm = TRUE)
  )
```

```{r}
weather_df %>%
  group_by(name) %>%
  mutate(temp_change = tmax - lag(tmax)) %>%
  summarize(
    temp_change_sd = sd(temp_change, na.rm = TRUE),
    temp_change_max = max(temp_change, na.rm = TRUE))
```

One other window function

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  mutate(
    tmax_rank = min_rank(tmax)
  )
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  mutate(tmax_rank = min_rank(tmax)) %>% 
  filter(tmax_rank < 4) %>% 
  arrange(name, month, tmax_rank)
```

