---
title: "Viz and Eda"
output: github_document
editor_options: 
  chunk_output_type: console
---
##Viz and Eda

```{r set up}
library(tidyverse)
library(ggridges)
```

## Let's import data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10, # degree C
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Let's make a scatter plot
```{r}
ggplot(weather_df, aes(x=tmin, y= tmax)) + geom_point()
```
Let's make the same scatter plot, but different

```{r}
weather_df %>% 
drop_na() %>% 
ggplot(aes(x=tmin, y=tmax))+ geom_point()
```
Let's keep making the same plot but different

```{r}
weather_scatterplot = weather_df %>% drop_na() %>% ggplot(aes(x=tmin, y=tmax))
weather_scatterplot+geom_point()
```

## Let's fancy this up a little bit
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)# se: CI level display?
```

Make seperate panels
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)+
  facet_grid(.~ name) # facet by row ~  facet by coln
```

Let's spice it up some
```{r}
weather_df %>% 
  ggplot(aes(x= date, y=tmax,color=name))+
  geom_point(aes(size=prcp),alpha=.3)+
  geom_smooth(se=FALSE)+
  facet_grid(.~ name)
```
```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```

##Univariate plots
Histograms, barplots, boxplots,violins...

```{r}
weather_df %>% 
  ggplot(aes(x=tmax))+
  geom_histogram()
```

more options
```{r}
weather_df %>% 
  ggplot(aes(x=tmax,fill=name))+
  geom_density(alpha =.3)
```

boxplots
```{r}
weather_df %>% 
  ggplot(aes(x= name, y= tmax), fill=name)+
  geom_boxplot(alpha =.3)
```

violin plots
```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), alpha = .5) + 
  stat_summary(fun = "median", color = "blue")
```

ridge plots
```{r}
weather_df %>% 
  ggplot(aes(x=tmax, y=name))+
  geom_density_ridges()
```

##saving and embedding plots

```{r}
weather_scatterplot = 
  weather_df %>% 
  ggplot(aes(x= date, y=tmax,color=name))+
  geom_point(aes(size=prcp),alpha=.3)+
  geom_smooth(se=FALSE)+
  facet_grid(.~ name)
weather_scatterplot
```

```{r}
ggsave("results/weather_scatterplot.pdf", weather_scatterplot,
       width = 8, height =9)
```

